### ISSUE TITLE
0.1.1 release planning

### ISSUE THREAD

**Issue by stblr** [stblr/mkw-sp#128]
- [x] #101
- [x] #87
- [x] #103
- [x] #73
- [x] #145
- [x] Input display tweaks
- [x] Write release notes
- [x] Fetch translations
- [x] Bump version string
- [x] Tag release
- [x] Update download links
