### ISSUE TITLE
0.1.5 release planning

### ISSUE THREAD

**Issue by stblr** [stblr/mkw-sp#255]
- [ ] Finish the Dolphin SD folder feature
- [ ] Use TRIM for SD cards if we can
- [ ] Maybe flush cache for SD cards (most of them don't support that)
- [ ] Do remaining cleanups for storage code
- [ ] Use relative paths for the `mkw-sp` directory in `FatStorage`
- [ ] Add a visual log to the loader
- [ ] #133
- [ ] #144
- [ ] #160
- [ ] #219
- [ ] #220
- [ ] #221
- [ ] Write release notes
- [ ] Fetch translations
- [ ] Bump version string
- [ ] Tag release
- [ ] Update download links
