### ISSUE TITLE
Online gameplay tracking issue

### ISSUE THREAD

**Issue by stblr** [stblr/mkw-sp#382]
## Room

- [ ] Handle access control
- [ ] Join a room
- [ ] Leave a room
- [ ] Spectate a room
- [ ] Change the room host
- [ ] Send chat messages
- [ ] Change room settings
- [ ] Start a room
- [ ] Choose character/vehicle/drift
- [ ] Vote for a track
- [ ] Synchronize on race start
- [ ] Synchronize on race end
- [ ] Race recordings
- [ ] Fast rejoin

## Race

- [ ] Send inputs
- [ ] Send player positions
- [ ] Apply player rollback
- [ ] Send item positions
- [ ] Apply item rollback

## Teams

- [ ] More than 2 teams offline
- [ ] More than 2 teams online

## Master server

- [ ] Register accounts
- [ ] Connect
- [ ] List rooms
- [ ] Create room
- [ ] Join room
- [ ] Add friends
- [ ] Remove friends
- [ ] List friends
- [ ] Join friend
- [ ] Handle VR/whatever

**Comment by vabold** [comment]
We should add a task for timeouts after `Handle access control` in Room.
