### ISSUE TITLE
Offline team mode tracking issue

### ISSUE THREAD

**Issue by stblr** [stblr/mkw-sp#407]
- [x] Basic implementation
- [x] Decide what to do with the blue team color
- [x] Reorder the team colors
- [x] Fix the congratulations text color in solo mode
- [x] Improve the "DRAW" text color
- [x] Characters should not cheer when hitting their teammates
- [x] The team overview should handle the colors like the rest
- [x] The team results (at the end of a race) should handle the colors like the rest
- [x] Finish the colorblind mode
- [x] Check UI sound effects
- [x] Engine classes
- [x] Handle ties
- [x] Battle mode
- [x] Music at end of race/battle
