### ISSUE TITLE
RoomManager fixes

### ISSUE THREAD

**Issue by stblr** [stblr/mkw-sp#448]
- [ ] Merge handlers
- [ ] Merge calls when possible
- [ ] Selectively hide room buttons
- [ ] Handle disconnects
- [ ] Support other team selection settings
- [ ] Rename "close" to "start"
- [ ] Only run calc once per frame, or adapt timers
- [ ] Make the UI more robust on error
- [ ] Add settings bounds checking
- [ ] Remove the Team GP button
