### ISSUE TITLE
CourseSelectPage tracking issue

### ISSUE THREAD

**Issue by stblr** [stblr/mkw-sp#503]
- [x] Rewrite `MultiDriftSelectPage::onButtonFront`
- [x] Consider saving the last selection like the base game
- [x] Do not always try to go to the `DriftSelectPage` when pressing B
- [x] Add online support
- [x] Remove asm patches
- [x] Preload previous/next page
- [x] Only show the scroll bar if needed
- [x] Support battle
- [x] Fix the text width in 16:9 for good
- [x] Fix the crash when going back in multiplayer
- [x] Preload thumbnails as soon as we know the gamemode

**Comment by stblr** [comment]
Random buttons have been moved to #697.
