### ISSUE TITLE
Rust game server feature parity tracking issue

### ISSUE THREAD

**Issue by stblr** [stblr/mkw-sp#547]
## Room

- [x] Join a room
- [x] Leave a room
- [x] Close the room when the host leaves
- [ ] Send chat messages
- [ ] Change room settings
- [ ] Start a room
- [ ] Select teams (was unfinished)
- [ ] Choose character/vehicle/drift
- [ ] Vote for a track
