### ISSUE TITLE
0.1.10 release planning

### ISSUE THREAD

**Issue by stblr** [stblr/mkw-sp#576]
- [x] Write release notes
- [x] Fetch translations
- [x] Bump version string
- [x] Tag release
- [x] Update download links
